name: Build DLL

on:
  push:
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce

      - name: Install vcpkg and curl
        run: |
            git clone https://github.com/microsoft/vcpkg.git
            .\vcpkg\bootstrap-vcpkg.bat

      - name: Install libcurl
        run: |
            .\vcpkg\vcpkg.exe install curl[core,ssl] --triplet x86-windows-static

      - name: Integrate vcpkg with MSBuild
        run: |
            .\vcpkg\vcpkg.exe integrate install

      - name: Update Plugin Version
        if: github.ref_type == 'tag'
        run: |
          $tag = $env:GITHUB_REF -replace 'refs/tags/', ''
          (Get-Content -Path "vSMR\SMRPlugin.hpp") -replace '#define MY_PLUGIN_VERSION.*', "#define MY_PLUGIN_VERSION   \"$tag\"" | Set-Content -Path "vSMR\SMRPlugin.hpp"

      - name: Build DLL
        run: msbuild vSMR.sln /p:Configuration=Release /p:Platform='Win32' /p:VcpkgTriplet=x86-windows-static /m

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vSMR.dll
          path: Release/vSMR.dll

      - name: Upload to Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        if: github.ref_type == 'tag'
        with:
          files: |
            Release/vSMR.dll